### PR TITLE
rebranding AdminBro to AdminJs

### PR DESCRIPTION
**Pull request by everythinginjs**
Hi, I have replaced adminbro to adminjs just you need to change the about of the repo to AdminJs as well as the link of the repo should be admin-js-users-permissions, thanks for letting me contribute. 🤟

### CODE REVIEW

**Comment by johnyvelho** [comment]
Hello @Amixengineer ,

Thank you for the collaboration and sorry for taking so long.
I actually sent you an invite some time ago to be a maintainer of this repository, since I won't have time to do that. That way you will be able to keep updating it if you wish so.
Also, we can't change the package name, since it's published using the name admin-bro-users-permissions

**Comment by everythinginjs** [comment]
Hey @johnyvelho,  got it but I have not seen the invitation that time and it is expired now please re-invite me again.

**Comment by johnyvelho** [comment]
done @Amixengineer

**Review by everythinginjs — COMMENTED** [review]
README RE-branding

**Pull request merged**
